---
abstract: 'An Asynchronous and multi channel Perl AMQP client.'
author:
  - 'Masahito Ikuta <cooldaemon@gmail.com>'
build_requires:
  Test::Exception: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RabbitFoot
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 0
  Config::Any: 0
  Coro: 0
  Coro::AnyEvent: 0
  File::ShareDir: 0
  JSON::XS: 0
  List::MoreUtils: 0
  Moose: 0
  MooseX::App::Cmd: 0
  MooseX::AttributeHelpers: 0
  MooseX::ConfigFromFile: 0
  Net::AMQP: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
